<a href="https://colab.research.google.com/github/angekonan715/DataScience-Projects/blob/main/starter_bankProject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [69]:
import pandas as pd
import numpy as np
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn import metrics
# !pip install lets_plot
from lets_plot import *
LetsPlot.setup_html()
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
campaign = pd.read_csv('https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/bank.csv')

## Data Explorartion

*Missing Value*

In [70]:
# 5 first rows
campaign.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [71]:
campaign.tail()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
37064,73,retired,married,professional.course,no,yes,no,cellular,nov,fri,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
37065,46,blue-collar,married,professional.course,no,no,no,cellular,nov,fri,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
37066,56,retired,married,university.degree,no,yes,no,cellular,nov,fri,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
37067,44,technician,married,professional.course,no,no,no,cellular,nov,fri,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
37068,74,retired,married,professional.course,no,yes,no,cellular,nov,fri,3,999,1,failure,-1.1,94.767,-50.8,1.028,4963.6,no

In [93]:
# replace value 999 from the pdays column to 0
campaign['pdays'] = campaign['pdays'].replace(999, 0)

In [94]:
# campaign['campaign'] = campaign['campaign'].astype('category')

# Encode our features and target as needed
features = [#'nr.employed',
                     #'euribor3m',
                    #'cons.price.idx',
                     #'emp.var.rate',
                     #'contact',
                     #'loan',
                     'pdays',
                     'campaign',
                     'poutcome',
                     'education']
X = pd.get_dummies(campaign[features], drop_first=True)
y = campaign['y']

In [95]:
# Split our data into training and test data, with 30% reserved for testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [96]:
# Build the decision tree
clf = DecisionTreeClassifier()

# Train it
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

# Test it
clf.score(X_test, y_test)

DecisionTreeClassifier()

0.9050445103857567

In [97]:

## test our model
y_pred = clf.predict(X_test)
## Evaluate our classification model: Decision tree
clf_report = metrics.classification_report(y_pred, y_test)
print(clf_report)

              precision    recall  f1-score   support

          no       0.99      0.91      0.95      7231
         yes       0.16      0.69      0.27       183

    accuracy                           0.91      7414
   macro avg       0.58      0.80      0.61      7414
weighted avg       0.97      0.91      0.93      7414