<a href="https://colab.research.google.com/github/angekonan715/DataScience-Projects/blob/main/starter_bankProject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [182]:
import pandas as pd
import numpy as np
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn import metrics
!pip install lets_plot
from lets_plot import *
LetsPlot.setup_html()
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
campaign = pd.read_csv('https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/bank.csv')

Requirement already satisfied: lets_plot in /usr/local/lib/python3.11/dist-packages (4.5.2)
Requirement already satisfied: pypng in /usr/local/lib/python3.11/dist-packages (from lets_plot) (0.20220715.0)
Requirement already satisfied: palettable in /usr/local/lib/python3.11/dist-packages (from lets_plot) (3.3.3)

In [183]:
campaign.info()
campaign.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37069 entries, 0 to 37068
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             37069 non-null  int64
 1   job             37069 non-null  object
 2   marital         37069 non-null  object
 3   education       37069 non-null  object
 4   default         37069 non-null  object
 5   housing         37069 non-null  object
 6   loan            37069 non-null  object
 7   contact         37069 non-null  object
 8   month           37069 non-null  object
 9   day_of_week     37069 non-null  object
 10  campaign        37069 non-null  int64
 11  pdays           37069 non-null  int64
 12  previous        37069 non-null  int64
 13  poutcome        37069 non-null  object
 14  emp.var.rate    37069 non-null  float64
 15  cons.price.idx  37069 non-null  float64
 16  cons.conf.idx   37069 non-null  float64
 17  euribor3m       37069 non-null  float64
 18  nr.employed     37069 non-null  float64
 19  y               37069 non-null  object
dtypes: float64(5), int64(4), object(11)
memory usage: 5.7+ MB

,age,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed
count,37069.000000,37069.000000,37069.000000,37069.000000,37069.000000,37069.000000,37069.000000,37069.000000,37069.000000
mean,40.025493,2.564407,962.221803,0.173730,0.081526,93.576551,-40.494829,3.621945,5167.010650
std,10.435288,2.764084,187.531477,0.496159,1.572287,0.579339,4.628895,1.734496,72.294476
min,17.000000,1.000000,0.000000,0.000000,-3.400000,92.201000,-50.800000,0.634000,4963.600000
25%,32.000000,1.000000,999.000000,0.000000,-1.800000,93.075000,-42.700000,1.344000,5099.100000
50%,38.000000,2.000000,999.000000,0.000000,1.100000,93.749000,-41.800000,4.857000,5191.000000
75%,47.000000,3.000000,999.000000,0.000000,1.400000,93.994000,-36.400000,4.961000,5228.100000
max,98.000000,56.000000,999.000000,7.000000,1.400000,94.767000,-26.900000,5.045000,5228.100000

In [184]:
ggplot(campaign, aes(x='cons.price.idx', y = 'cons.conf.idx')) +\
 geom_point() +\
 geom_smooth(method='lm') +\
 labs(title='Consumer Price Index vs Consumer Confidence Index')

In [185]:
#relationship between cons.price.idx and y
ggplot(campaign, aes(x='cons.price.idx', y = 'y')) +\
 geom_point() +\
 geom_smooth(method='lm') +\
 labs(title='Consumer Price Index vs Subscription')

## Data Explorartion

*Missing Value*

In [186]:
# 5 first rows
campaign.head()
# campaign.default.value_counts()
#great
campaign.info()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37069 entries, 0 to 37068
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             37069 non-null  int64
 1   job             37069 non-null  object
 2   marital         37069 non-null  object
 3   education       37069 non-null  object
 4   default         37069 non-null  object
 5   housing         37069 non-null  object
 6   loan            37069 non-null  object
 7   contact         37069 non-null  object
 8   month           37069 non-null  object
 9   day_of_week     37069 non-null  object
 10  campaign        37069 non-null  int64
 11  pdays           37069 non-null  int64
 12  previous        37069 non-null  int64
 13  poutcome        37069 non-null  object
 14  emp.var.rate    37069 non-null  float64
 15  cons.price.idx  37069 non-null  float64
 16  cons.conf.idx   37069 non-null  float64
 17  euribor3m       37069 non-null  float64
 18  nr.employed     37069 non-null  float64
 19  y               37069 non-null  object
dtypes: float64(5), int64(4), object(11)
memory usage: 5.7+ MB

In [187]:
campaign.loan.value_counts()

loan
no         30590
yes         5585
unknown      894
Name: count, dtype: int64

In [188]:
campaign.tail()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
37064,73,retired,married,professional.course,no,yes,no,cellular,nov,fri,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
37065,46,blue-collar,married,professional.course,no,no,no,cellular,nov,fri,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
37066,56,retired,married,university.degree,no,yes,no,cellular,nov,fri,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
37067,44,technician,married,professional.course,no,no,no,cellular,nov,fri,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
37068,74,retired,married,professional.course,no,yes,no,cellular,nov,fri,3,999,1,failure,-1.1,94.767,-50.8,1.028,4963.6,no

In [103]:
# replace value 999 from the pdays column to 0
#campaign['pdays'] = campaign['pdays'].replace(999, 0)
campaign.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'campaign', 'pdays', 'previous',
       'poutcome', 'emp.var.rate', 'cons.price.idx', 'cons.conf.idx',
       'euribor3m', 'nr.employed', 'y'],
      dtype='object')

In [174]:
# campaign['campaign'] = campaign['campaign'].astype('category')

# Encode our features and target as needed
features = ['job',
            'loan',
            'housing',
            #'month',
            'day_of_week',
            'pdays',
            'campaign',
            'poutcome',
            'education',
            'emp.var.rate',
            #'default',
            'cons.price.idx',
            'cons.conf.idx',
            'euribor3m',
            'nr.employed'

            ]
#campaign_filtered = campaign.drop(columns=['y', 'default'])
#campaign_filtered = campaign_filtered.filter(regex='^(?!.*unknown).*$', axis=1)
X = pd.get_dummies(campaign[features], drop_first=True)
#X = X.filter(regex='^(?!.*unknown).*$', axis=1)
y = campaign['y']

In [169]:
X.columns
X.head()

Index(['pdays', 'campaign', 'emp.var.rate', 'cons.price.idx', 'cons.conf.idx',
       'euribor3m', 'nr.employed', 'job_blue-collar', 'job_entrepreneur',
       'job_housemaid', 'job_management', 'job_retired', 'job_self-employed',
       'job_services', 'job_student', 'job_technician', 'job_unemployed',
       'job_unknown', 'loan_unknown', 'loan_yes', 'housing_unknown',
       'housing_yes', 'month_aug', 'month_dec', 'month_jul', 'month_jun',
       'month_mar', 'month_may', 'month_nov', 'month_oct', 'month_sep',
       'day_of_week_mon', 'day_of_week_thu', 'day_of_week_tue',
       'day_of_week_wed', 'poutcome_nonexistent', 'poutcome_success',
       'education_basic.6y', 'education_basic.9y', 'education_high.school',
       'education_illiterate', 'education_professional.course',
       'education_university.degree', 'education_unknown', 'default_unknown',
       'default_yes'],
      dtype='object')

,pdays,campaign,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,job_blue-collar,job_entrepreneur,job_housemaid,...,poutcome_success,education_basic.6y,education_basic.9y,education_high.school,education_illiterate,education_professional.course,education_university.degree,education_unknown,default_unknown,default_yes
0,0,1,1.1,93.994,-36.4,4.857,5191.0,False,False,True,...,False,False,False,False,False,False,False,False,False,False
1,0,1,1.1,93.994,-36.4,4.857,5191.0,False,False,False,...,False,False,False,True,False,False,False,False,True,False
2,0,1,1.1,93.994,-36.4,4.857,5191.0,False,False,False,...,False,False,False,True,False,False,False,False,False,False
3,0,1,1.1,93.994,-36.4,4.857,5191.0,False,False,False,...,False,True,False,False,False,False,False,False,False,False
4,0,1,1.1,93.994,-36.4,4.857,5191.0,False,False,False,...,False,False,False,True,False,False,False,False,False,False

In [175]:
# Split our data into training and test data, with 30% reserved for testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [176]:

# Build the decision tree
clf = DecisionTreeClassifier(class_weight='balanced', random_state=42)

# Train it
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

# Test it
clf.score(X_test, y_test)

DecisionTreeClassifier(class_weight='balanced', random_state=42)

0.8065821418937146

In [177]:

## test our model
y_pred = clf.predict(X_test)
## Evaluate our classification model: Decision tree
clf_report = metrics.classification_report(y_pred, y_test)
print(clf_report)

              precision    recall  f1-score   support

          no       0.87      0.91      0.89      6247
         yes       0.34      0.25      0.29      1167

    accuracy                           0.81      7414
   macro avg       0.60      0.58      0.59      7414
weighted avg       0.78      0.81      0.79      7414

In [178]:
# Access feature importance scores
feature_importances = clf.feature_importances_

# Create a DataFrame to display feature importances alongside feature names
feature_importance_df = pd.DataFrame({'Feature': X_train.columns, 'Importance': feature_importances})

# Sort by importance in descending order
feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)

# Display the DataFrame
print(feature_importance_df)
# Create a bar plot
# Create a ggplot bar plot
ggplot(feature_importance_df, aes(x='Feature', y='Importance')) + \
    geom_bar() + \
    coord_flip() + \
    labs(title='Feature Importance in Decision Tree', x='Feature', y='Importance')

                          Feature  Importance
6                     nr.employed    0.226738
1                        campaign    0.115314
5                       euribor3m    0.111320
4                   cons.conf.idx    0.068627
21                    housing_yes    0.049148
19                       loan_yes    0.030000
30          education_high.school    0.028950
15                 job_technician    0.026975
7                 job_blue-collar    0.023402
33    education_university.degree    0.021803
23                day_of_week_thu    0.021627
3                  cons.price.idx    0.020771
25                day_of_week_wed    0.020244
24                day_of_week_tue    0.020198
29             education_basic.9y    0.019602
10                 job_management    0.018301
22                day_of_week_mon    0.017115
0                           pdays    0.016465
13                   job_services    0.016455
32  education_professional.course    0.016234
12              job_self-employed    0.013018
8                job_entrepreneur    0.012490
11                    job_retired    0.012319
26           poutcome_nonexistent    0.010759
28             education_basic.6y    0.010700
34              education_unknown    0.010545
14                    job_student    0.009508
16                 job_unemployed    0.008993
9                   job_housemaid    0.007039
18                   loan_unknown    0.004717
20                housing_unknown    0.004135
17                    job_unknown    0.002972
2                    emp.var.rate    0.001855
27               poutcome_success    0.001493
31           education_illiterate    0.000171

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
fatal: could not read Username for 'https://github.com': No such device or address

In [179]:
#PREDICT ON THE MINI DATASET
bank_hold_mini = pd.read_csv('https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/bank_holdout_test_mini.csv')
#assign the same features to the mini dataset
mini_X = pd.get_dummies(bank_hold_mini[features])
#filter mini with all the columns of X not features
mini_X, _ = mini_X.align(X, join='inner', axis=1)
# mini_X = mini_X[['pdays', 'campaign',
#                         'poutcome_nonexistent', 'poutcome_success',
#                         'education_basic.6y', 'education_basic.9y',
#                         'education_high.school','education_illiterate',
#                         'education_professional.course','education_university.degree',
#                         'education_unknown']]
 #make a predictions column, filled in with the predictions
mini_X['predictions (y)'] = clf.predict(mini_X)
mini_X['predictions (y)'] = mini_X['predictions (y)'].replace('no',0)
mini_X['predictions (y)'] = mini_X['predictions (y)'].replace('yes',1)
predictions = mini_X['predictions (y)']

<ipython-input-179-6fc24f9943e7>:16: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  mini_X['predictions (y)'] = mini_X['predictions (y)'].replace('yes',1)

In [180]:
mini_X

,pdays,campaign,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,job_blue-collar,job_entrepreneur,job_housemaid,...,poutcome_nonexistent,poutcome_success,education_basic.6y,education_basic.9y,education_high.school,education_illiterate,education_professional.course,education_university.degree,education_unknown,predictions (y)
0,999,2,1.4,93.918,-42.7,4.962,5228.1,True,False,False,...,True,False,False,True,False,False,False,False,False,0
1,999,1,-1.8,92.893,-46.2,1.344,5099.1,False,False,False,...,True,False,False,False,True,False,False,False,False,0
2,3,1,-1.7,94.055,-39.8,0.739,4991.6,False,False,False,...,False,True,False,False,False,False,False,True,False,1
3,999,12,1.4,94.465,-41.8,4.959,5228.1,False,False,False,...,True,False,False,False,True,False,False,False,False,0
4,999,1,-0.1,93.200,-42.0,4.120,5195.8,False,False,False,...,True,False,False,False,True,False,False,False,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
405,999,3,-1.8,92.893,-46.2,1.250,5099.1,False,False,False,...,True,False,False,False,False,False,True,False,False,0
406,999,9,1.4,93.918,-42.7,4.962,5228.1,False,False,False,...,True,False,False,False,False,False,False,False,True,0
407,999,1,1.4,94.465,-41.8,4.967,5228.1,False,False,False,...,True,False,False,True,False,False,False,False,False,0
408,999,1,-0.1,93.200,-42.0,4.021,5195.8,False,False,False,...,True,False,False,False,False,False,False,True,False,0
409,999,1,-1.8,92.893,-46.2,1.334,5099.1,False,False,False,...,True,False,False,True,False,False,False,False,False,0

In [181]:
# Download my predictions columns as csv
from google.colab import files
predictions.to_csv('predictions.csv')
files.download('predictions.csv')

In [ ]:
mini_X['education_basic.6y'].value_counts()

# New Section

# New Section