<a href="https://colab.research.google.com/github/angekonan715/DataScience-Projects/blob/main/starter_bankProject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn import metrics
!pip install lets_plot
from lets_plot import *
LetsPlot.setup_html()
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
campaign = pd.read_csv('https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/bank.csv')

Collecting lets_plot
  Downloading lets_plot-4.5.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Collecting pypng (from lets_plot)
  Downloading pypng-0.20220715.0-py3-none-any.whl.metadata (13 kB)
Collecting palettable (from lets_plot)
  Downloading palettable-3.3.3-py2.py3-none-any.whl.metadata (3.3 kB)
Downloading lets_plot-4.5.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 21.6 MB/s eta 0:00:00
Downloading palettable-3.3.3-py2.py3-none-any.whl (332 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 332.3/332.3 kB 11.8 MB/s eta 0:00:00
Downloading pypng-0.20220715.0-py3-none-any.whl (58 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.1/58.1 kB 2.4 MB/s eta 0:00:00
Installing collected packages: pypng, palettable, lets_plot
Successfully installed lets_plot-4.5.2 palettable-3.3.3 pypng-0.20220715.0

## Data Explorartion

*Missing Value*

In [2]:
# 5 first rows
campaign.head()
# campaign.default.value_counts()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [3]:
campaign.loan.value_counts()

loan
no         30590
yes         5585
unknown      894
Name: count, dtype: int64

In [4]:
campaign.tail()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
37064,73,retired,married,professional.course,no,yes,no,cellular,nov,fri,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
37065,46,blue-collar,married,professional.course,no,no,no,cellular,nov,fri,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
37066,56,retired,married,university.degree,no,yes,no,cellular,nov,fri,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
37067,44,technician,married,professional.course,no,no,no,cellular,nov,fri,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
37068,74,retired,married,professional.course,no,yes,no,cellular,nov,fri,3,999,1,failure,-1.1,94.767,-50.8,1.028,4963.6,no

In [5]:
# replace value 999 from the pdays column to 0
#campaign['pdays'] = campaign['pdays'].replace(999, 0)

In [6]:
# campaign['campaign'] = campaign['campaign'].astype('category')

# Encode our features and target as needed
features = ['job',
            'loan',
            'pdays',
            'campaign',
            'poutcome',
            'education',
            'emp.var.rate']
#campaign_filtered = campaign.drop(columns=['y', 'default'])
#campaign_filtered = campaign_filtered.filter(regex='^(?!.*unknown).*$', axis=1)
X = pd.get_dummies(campaign[features], drop_first=True)
X = X.filter(regex='^(?!.*unknown).*$', axis=1)
y = campaign['y']

In [7]:
X.columns
X.head()

Index(['pdays', 'campaign', 'emp.var.rate', 'job_blue-collar',
       'job_entrepreneur', 'job_housemaid', 'job_management', 'job_retired',
       'job_self-employed', 'job_services', 'job_student', 'job_technician',
       'job_unemployed', 'loan_yes', 'poutcome_nonexistent',
       'poutcome_success', 'education_basic.6y', 'education_basic.9y',
       'education_high.school', 'education_illiterate',
       'education_professional.course', 'education_university.degree'],
      dtype='object')

,pdays,campaign,emp.var.rate,job_blue-collar,job_entrepreneur,job_housemaid,job_management,job_retired,job_self-employed,job_services,...,job_unemployed,loan_yes,poutcome_nonexistent,poutcome_success,education_basic.6y,education_basic.9y,education_high.school,education_illiterate,education_professional.course,education_university.degree
0,999,1,1.1,False,False,True,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
1,999,1,1.1,False,False,False,False,False,False,True,...,False,False,True,False,False,False,True,False,False,False
2,999,1,1.1,False,False,False,False,False,False,True,...,False,False,True,False,False,False,True,False,False,False
3,999,1,1.1,False,False,False,False,False,False,False,...,False,False,True,False,True,False,False,False,False,False
4,999,1,1.1,False,False,False,False,False,False,True,...,False,True,True,False,False,False,True,False,False,False

In [8]:
# Split our data into training and test data, with 30% reserved for testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [9]:

# Build the decision tree
clf = DecisionTreeClassifier()

# Train it
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

# Test it
clf.score(X_test, y_test)

DecisionTreeClassifier()

0.8835985972484489

In [10]:

## test our model
y_pred = clf.predict(X_test)
## Evaluate our classification model: Decision tree
clf_report = metrics.classification_report(y_pred, y_test)
print(clf_report)

              precision    recall  f1-score   support

          no       0.97      0.90      0.94      7059
         yes       0.20      0.49      0.29       355

    accuracy                           0.88      7414
   macro avg       0.59      0.70      0.61      7414
weighted avg       0.94      0.88      0.91      7414

In [11]:
q = list(set(X.columns))
q

['job_student',
 'pdays',
 'job_housemaid',
 'loan_yes',
 'job_entrepreneur',
 'education_basic.6y',
 'education_basic.9y',
 'campaign',
 'education_illiterate',
 'job_management',
 'job_retired',
 'emp.var.rate',
 'poutcome_nonexistent',
 'poutcome_success',
 'job_blue-collar',
 'job_self-employed',
 'education_professional.course',
 'education_high.school',
 'job_unemployed',
 'education_university.degree',
 'job_services',
 'job_technician']

In [12]:
#PREDICT ON THE MINI DATASET
bank_hold_mini = pd.read_csv('https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/bank_holdout_test_mini.csv')
#assign the same features to the mini dataset
mini_X = pd.get_dummies(bank_hold_mini[features])
#filter mini with all the columns of X not features
mini_X = mini_X.align(X, join='inner', axis=1)
# mini_X = mini_X[['pdays', 'campaign',
#                         'poutcome_nonexistent', 'poutcome_success',
#                         'education_basic.6y', 'education_basic.9y',
#                         'education_high.school','education_illiterate',
#                         'education_professional.course','education_university.degree',
#                         'education_unknown']]
 #make a predictions column, filled in with the predictions
mini_X['predictions (y)'] = clf.predict(mini_X)
mini_X['predictions (y)'] = mini_X['predictions (y)'].replace('no',0)
mini_X['predictions (y)'] = mini_X['predictions (y)'].replace('yes',1)
predictions = mini_X['predictions (y)']

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
mini_X

In [ ]:
# Download my predictions columns as csv
from google.colab import files
predictions.to_csv('predictions.csv')
files.download('predictions.csv')

In [ ]:
mini_X['education_basic.6y'].value_counts()

# New Section

# New Section